### ISSUE TITLE
Creation of ground truth .dcm for WinstonLutz

### ISSUE THREAD

**Issue by caro314** [jrkerns/pylinac#436]
Hi together, maybe someone can help me out, would really appreciate any help.
If this is not the right context here, please be gentle, it is my first issue on github.

I am trying to build ground truth synthetic dicoms to test a STX QA tool in which I have built in pylinac WinstonLutz.

My idea was simple but turns out "just writing a dicom" is not as simple as I thought. My vision:´is the following
-  I want to create a 3D sphere (maybe in numpy?) with density 1 when inside the sphere and 0 otherwise. Radius, center etc. should be customizable. 
- Then, I virtually project the sphere into different BEV planes, dependent on gantry angle (for now, let's say G0, G90, G180, G270).
- From these projections I want to generate DICOM files which I can analyze with pylinac winstonlutz. (These projections represent the MV-projections I would normally acquire when performing WLtest at the linac)
- In these synthetic dicoms, the center of the image is the real virtual isocenter. So the deviation of the sphere's center position from 0 is the virtual deviation of my winstonlutz test.

**Describe alternatives you've considered**
- I approached this by creating a sphere and its projections as numpy arrays.
- I wanted to use SimpleITK to convert the array into dcm but this fails silently. 
- My main issue is, that I am failing at this - to me "easy"- task. Is it really that complicated to create a synthetic dicom from a _projection_ only ?

<img width="592" alt="pylinac 3d spheres" src="https://user-images.githubusercontent.com/54809072/228534589-1e3105d2-7125-4e5f-b305-113eb1f1e80f.png">

**Additional context**
- I dot not need a dicom of the whole sphere object as this is not necessary
- Ideally, I can define a perfect square in the projection, too (representing the MLC leaves).

I am aware that there have been tests implemented recently. However, my co-physicist are not well trained with the concept of testing in software development ;) I therefore want to demonstrate the functionality of pylinac winstonlutz with my ground truth images.
Really appreciate any help, here. 

Best,
Cati

**Comment by jrkerns** [comment]
Hello Cati, 
        I can hopefully help. First though, this is more of a discussion vs an "issue" and is better suited for the google forum: https://groups.google.com/g/pylinac. 

If I'm understanding correctly, I think we can shortcut your problem and use the image generator module in pylinac. You can see examples and code to create the DICOMs here: https://pylinac.readthedocs.io/en/latest/winston_lutz.html#benchmarking-the-algorithm. I also had issues trying to prove that the WL algorithm was correct. Real data always has some error it in, and identifying whether that error was accurate proved tricky, which is why I made the synthetic image generator. If that solves your problem then I think that's it. 

To answer the question about creating dicoms from an array, it is very possible to do so. The excellent pydicom library can help you there: https://pydicom.github.io/pydicom/stable/tutorials/dataset_basics.html. For the image itself, you should write back to bytes and also adjust the Rows and Columns tags so when you read it again it all matches. Here's how pylinac does it: https://github.com/jrkerns/pylinac/blob/master/pylinac/core/image.py#L1040-L1055

**Comment by caro314** [comment]
Hi,
thank you for the fast answer - okay, next time I'll post it in the forum! 

You got my request quite right, as you described the problem perfectly:
> I also had issues trying to prove that the WL algorithm was correct. Real data always has some error it in, and identifying whether that error was accurate proved tricky, which is why I made the synthetic image generator. If that solves your problem then I think that's it.

I will check out all your suggestions and report the outcome :-)
