### ISSUE TITLE
I want to convert .dlg fie to .cvs

### ISSUE THREAD

**Issue by amitkumart** [jrkerns/pylinac#447]
Hello I am trying converting .dlg fie to .cvs using python, this requires pandas and Pylinac lib both have been installed  
I am using Jupiter notebook
import pylinac
import pandas as pd
dlg_file = pylinac.BinaryFile.open('C:/Users/chami/Downloads/archive/A20230325135709_2023757.dlg')

This is the error

AttributeError: module 'pylinac' has no attribute 'BinaryFile'

I tried already re-installing pylinac but still the same

I also tried 
import pylinac
import pandas as pd
from pylinac import Dynalog
dlog_path = "C:/Users/chami/Downloads/archive/A20230325135709_2023757.dlg")
dlog = Dynalog.from_binary(dlog_path)

AttributeError: type object 'Dynalog' has no attribute 'from_binary'

**Comment by jrkerns** [comment]
I'm not sure where you're getting your information, but there is no `BinaryFile` class nor a `.from_binary` method, especially for a dynalog since it's already a CSV file. Any basic text editor can open a .dlg file. If that's all you're after you don't need pylinac. Pandas alone would suffice. See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html. If you want to use the log analyzer for analyzing data the documentation is here: https://pylinac.readthedocs.io/en/latest/log_analyzer.html
